
const markerbig: Marker[] = [
  {
    id: 1,
    title: "Stage - 1",
    description: "This is the campus store where you can buy essentials.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "49%", left: "89%" },
  },
  {
    id: 2,
    title: "Stage - 2",
    description: "The hostel block for students.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "85%", left: "76%" },
  },
  {
    id: 3,
    title: "Stage - 3",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "11%", left: "24%" },
  },
  {
    id: 4,
    title: "Stage - 4",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "22%", left: "78%" },
  },
  {
    id: 5,
    title: "Stage - 5",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "39%", left: "89%" },
  },
  {
    id: 6,
    title: "Stage - 6",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "44%", left: "89%" },
  },
  {
    id: 7,
    title: "Reception",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "29%", left: "85%" },
  },
  {
    id: 8,
    title: "Fest Office",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "59%", left: "75%" },
  },
  {
    id: 9,
    title: "Clok Room",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "29%", left: "15%" },
  },
  {
    id: 10,
    title: "Mini Expo",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "73%", left: "59%" },
  },
  {
    id: 11,
    title: "Main entrance",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/entrance.webp?raw=true",
    position: { top: "90%", left: "31%" },
  },
  {
    id: 12,
    title: "PMSA Masjid",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/masjid.webp?raw=true",
    position: { top: "87%", left: "12%" },
  },
  {
    id: 13,
    title: "PMSA Main office",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/mainoff.webp?raw=true",
    position: { top: "56%", left: "20%" },
  },
  {
    id: 14,
    title: "Parking",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/parking.webp?raw=true",
    position: { top: "35%", left: "31%" },
  },
  {
    id: 15,
    title: "Canteen",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/canteen.webp?raw=true",
    position: { top: "26%", left: "67%" },
  },
  {
    id: 16,
    title: "Toilet & Shower",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/toilet.webp?raw=true",
    position: { top: "24%", left: "94%" },
  },
  {
    id: 17,
    title: "Store",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/store.webp?raw=true",
    position: { top: "46%", left: "76%" },
  },
  {
    id: 18,
    title: "Hostel",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://github.com/trend-setting/gallery/blob/main/hostel.webp?raw=true",
    position: { top: "65%", left: "54%" },
  },
  {
    id: 19,
    title: "PMSA Wafy college",
    description: "Wafy college of pmsa campus with modern library",
    image: "https://github.com/trend-setting/gallery/blob/main/clgphoto.webp?raw=true",
    position: { top: "75%", left: "68%" },
  },
  {
    id: 20,
    title: "PMSA Hospital",
    description: "Enjoy a variety of meals and snacks here.",
    image: "https://shorturl.at/xnVsq",
    position: { top: "90%", left: "83%" },
  },
];

export default markerbig