

const markersmall: Marker[] = [
  {
    id: 1,
    title: "Stage - 1",
    description: "This is the campus store where you can buy essentials.",
    image: "/store.jpg",
    position: { top: "46%", left: "91%" },
  },
  {
    id: 2,
    title: "Stage - 2",
    description: "The hostel block for students.",
    image: "/hostel.jpg",
    position: { top: "65%", left: "52%" },
  },
  {
    id: 3,
    title: "Stage - 3",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 4,
    title: "Stage - 4",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 5,
    title: "Stage - 5",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 6,
    title: "Stage - 6",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 7,
    title: "Reception",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 8,
    title: "Fest Office",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 9,
    title: "Clok Room",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 10,
    title: "Mini Expo",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 11,
    title: "Main entrance",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 12,
    title: "PMSA Masjid",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 13,
    title: "PMSA Main office",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 14,
    title: "Parking",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 15,
    title: "Canteen",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 16,
    title: "Toilet & Shower",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 17,
    title: "Store",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 18,
    title: "Hostel",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 19,
    title: "PMSA Wafy college",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
  {
    id: 20,
    title: "PMSA Hospital",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "26%", left: "69%" },
  },
];

export default markersmall