

const markersmall: Marker[] = [
  {
    id: 1,
    title: "Stage - 1",
    description: "This is the campus store where you can buy essentials.",
    image: "/store.jpg",
    position: { top: "92%", left: "49%" },
  },
  {
    id: 2,
    title: "Stage - 2",
    description: "The hostel block for students.",
    image: "/hostel.jpg",
    position: { top: "78%", left: "16%" },
  },
  {
    id: 3,
    title: "Stage - 3",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "21%", left: "88%" },
  },
  {
    id: 4,
    title: "Stage - 4",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "80%", left: "77%" },
  },
  {
    id: 5,
    title: "Stage - 5",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "92%", left: "62%" },
  },
  {
    id: 6,
    title: "Stage - 6",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "92%", left: "55%" },
  },
  {
    id: 7,
    title: "Reception",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "88%", left: "71%" },
  },
  {
    id: 8,
    title: "Fest Office",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "77%", left: "40%" },
  },
  {
    id: 9,
    title: "Clok Room",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "12%", left: "70%" },
  },
  {
    id: 10,
    title: "Mini Expo",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "56%", left: "24%" },
  },
  {
    id: 11,
    title: "Main entrance",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "30%", left: "12%" },
  },
  {
    id: 12,
    title: "PMSA Masjid",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "12%", left: "14%" },
  },
  {
    id: 13,
    title: "PMSA Main office",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "19%", left: "43%" },
  },
  {
    id: 14,
    title: "Parking",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "28%", left: "65%" },
  },
  {
    id: 15,
    title: "Canteen",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "69%", left: "74%" },
  },
  {
    id: 16,
    title: "Toilet & Shower",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "98%", left: "80%" },
  },
  {
    id: 17,
    title: "Store",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "79%", left: "53%" },
  },
  {
    id: 18,
    title: "Hostel",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "52%", left: "38%" },
  },
  {
    id: 19,
    title: "PMSA Wafy college",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "69%", left: "24%" },
  },
  {
    id: 20,
    title: "PMSA Hospital",
    description: "Enjoy a variety of meals and snacks here.",
    image: "/canteen.jpg",
    position: { top: "87%", left: "20%" },
  },
];

export default markersmall